name: Terraform OIDC Apply with Manual Approval

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

  workflow_dispatch:      
    inputs:
      environment:
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage
          - prod   

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/${{ github.event.inputs.environment }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC Pro
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::504006486060:role/tf-gh-role
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init & Migrate
        run: terraform init 

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars

  terraform-dev-apply:
    if: github.ref == 'refs/heads/main'
    name: Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment:
      name: dev
    defaults:
      run:
        working-directory: environments/${{ github.event.inputs.environment }}  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

          #      - name: Show OIDC subject
          #env:
          #GIT_REPO: ${{ github.repository }}
          #GIT_REF: ${{ github.ref }}  
          # run: echo "OIDC subject: repo=${GIT_REPO} ref=${GIT_REF}"

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::504006486060:role/tf-gh-role
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve  -var-file=terraform.tfvars

